Add getter and setter for vhd informations
LycaniteGroup/Lycanite pull request #48
Opened 2020-12-04 15:29 UTC by Vaati3

Create get and set methods for the virtual disk informations

2020-12-09 16:15 UTC, theocerutti requested changes

2020-12-09 16:15 UTC, theocerutti commented on VFS/VirtualDisk.cpp
> +void VirtualDisk::setDiskInfo(std::wstring parentPath, DWORD physicalSectorSize)
You must put const reference here for parentPath

2020-12-09 16:15 UTC, theocerutti commented on VFS/VirtualDisk.cpp
> +void VirtualDisk::setDiskInfo(std::wstring parentPath, DWORD physicalSectorSize)
Moreover, This function should be removed because we already have resize function and AddVirtualParentPath

2020-12-09 16:15 UTC, theocerutti commented on VFS/VirtualDisk.cpp
> +        NULL);
Set nullptr for all of your call of GetVirtualDiskInformation

2020-12-09 16:39 UTC, Vaati3 commented on VFS/VirtualDisk.cpp
> +void VirtualDisk::setDiskInfo(std::wstring parentPath, DWORD physicalSectorSize)
Done, i removed it

2020-12-09 16:40 UTC, Vaati3 commented on VFS/VirtualDisk.cpp
> +        NULL);
all the NULL have been replaced by nullptr

2020-12-09 16:53 UTC, theocerutti requested changes

2020-12-09 16:53 UTC, theocerutti commented on VFS/VirtualDisk.cpp
> +    opStatus = GetVirtualDiskInformation(
You don't check opStatus for each call.
Suggestion: you should create a private function that call GetVirtualDiskInformation with a FLAG parameter, it will fill _diskInfo and will check opStatus at the same time.

2020-12-09 17:24 UTC, AntoineMaillard06 submitted a review, later dismissed

2020-12-09 17:25 UTC, theocerutti approved these changes

2020-12-09 17:29 UTC, MathildeCouston submitted a review, later dismissed

2020-12-09 17:29 UTC, Vaati3 commented on VFS/VirtualDisk.cpp
> +    opStatus = GetVirtualDiskInformation(
Done

2020-12-09 17:37 UTC, AntoineMaillard06 submitted a review, later dismissed

2020-12-09 17:41 UTC, mic16 submitted a review, later dismissed
LGTM

2020-12-09 17:50 UTC, Shiranuit requested changes

2020-12-09 17:50 UTC, Shiranuit commented on VFS/VirtualDisk.cpp
> +    ULONG diskInfoSize = sizeof(GET_VIRTUAL_DISK_INFO);
`GET_VIRTUAL_DISK_INFO` is a struct made with several union as described [here](https://docs.microsoft.com/en-us/windows/win32/api/virtdisk/ns-virtdisk-get_virtual_disk_info), the data of the struct is populated differently if the `Version` parameter is set to a specific flag.

This means if you use the same `GET_VIRTUAL_DISK_INFO` struct and do a `GetVirtualDiskInformation` passing this same struct over and over only changing the `Version` flag, every data will be overwritten by the next `GetVirualDiskInformation`,  because it uses `unions` and `unions` share their memory location

2020-12-09 18:07 UTC, Vaati3 commented on VFS/VirtualDisk.cpp
> +    ULONG diskInfoSize = sizeof(GET_VIRTUAL_DISK_INFO);
thx, i have fixed the issue

2020-12-10 09:13 UTC, Shiranuit approved these changes

2020-12-10 09:21 UTC, MathildeCouston submitted a review, later dismissed

2020-12-10 14:28 UTC, theocerutti approved these changes

2020-12-10 14:54 UTC, AntoineMaillard06 approved these changes

2020-12-10 14:55 UTC, MathildeCouston approved these changes

2020-12-10 14:58 UTC, yoanVESSIERE approved these changes
LGTM

2020-12-10 14:58 UTC, mic16 approved these changes
LGTM

2020-12-10 15:01 UTC, cyrilbegard approved these changes
LGTM

2020-12-10 15:02 UTC, merged