open and close executable
LycaniteGroup/Lycanite pull request #69
Opened 2020-12-09 14:56 UTC by yoanVESSIERE

Add the ability to open Executable without the drag and drop, and when tab are closed, the application should be closed too, will be able the close the tab if the application is closed

2020-12-10 17:33 UTC, Vaati3 commented on App/TabTemplate.cs
> +            Debug.WriteLine(Path.GetFileName(filename));
Is that a debug line?

2020-12-10 17:36 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +            Debug.WriteLine(Path.GetFileName(filename));
Removed !

2020-12-10 17:37 UTC, Vaati3 commented on App/TabTemplate.cs
> +            Debug.WriteLine(Path.GetFileName(filename));
Nice

2020-12-10 17:40 UTC, Vaati3 submitted a review, later dismissed

2020-12-10 17:45 UTC, MathildeCouston approved these changes
LGTM

2020-12-10 18:00 UTC, AntoineMaillard06 requested changes

2020-12-10 18:00 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
> +            if (collection.Count > 0)
Useless statement : `foreach` handle this

2020-12-10 18:03 UTC, AntoineMaillard06 requested changes

2020-12-10 18:03 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
> +                        childProcess.Kill();
No function or statement to check before `kill` method

2020-12-10 18:05 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
>          private void Form1_DragDrop(object sender, DragEventArgs e)
What's `Form1` ?

2020-12-10 18:06 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
>          private void Form1_DragDrop(object sender, DragEventArgs e)
Be more explicit please.

2020-12-10 18:10 UTC, Vaati3 commented on App/LycaniteApplication.cs
> +                        childProcess.Kill();
and the spelling is not quite right : "Le process n'est pas terminé"

2020-12-10 18:23 UTC, Shiranuit requested changes

2020-12-10 18:23 UTC, Shiranuit commented on App/LycaniteApplication.cs
> +                    _processes.Add(name, proc_tmp);
If you start the same application two times, the name will be the same creating a conflict

2020-12-10 18:23 UTC, Shiranuit commented on App/LycaniteApplication.cs
> +                        _processes.Add(name, proc_tmp);
If you start the same application two times, the name will be the same creating a conflict

2020-12-10 18:23 UTC, Shiranuit commented on App/TabTemplate.cs
> +                        MessageBox.Show("ERROR: File already in the autorization list");
```suggestion

```
This should not be treated as an error, we should just ignore it

2020-12-10 18:23 UTC, Shiranuit commented on App/TabTemplate.cs
> +                    _fileListAuthorize.Add(Path.GetFileName(fileDialog.FileName), fileDialog.FileName);
You didn't check if the folder was already added

2020-12-10 18:23 UTC, Shiranuit commented on App/TabTemplate.cs
> +                    addDirList(fileDialog.FileName);
You should not add it to the list if the file is already present in  it

2020-12-10 18:23 UTC, Shiranuit commented on App/TabTemplate.cs
> +                    addDirList(fileDialog.FileName);
```suggestion
                    addPathToList(fileDialog.FileName);

```
I think this method should be rename since it doesn't add only directory to  a list

2020-12-10 18:26 UTC, Shiranuit commented on App/LycaniteApplication.cs
>          private void Form1_DragDrop(object sender, DragEventArgs e)
That's the default windows form for you application, this is defaulted by the Windows Form Editor of Visual Studio and is well known by the community to the main windows form, like you would call the entry point of a program `main`

2020-12-10 18:34 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +                    addDirList(fileDialog.FileName);
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                    _processes.Add(name, proc_tmp);
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                        _processes.Add(name, proc_tmp);
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +                        MessageBox.Show("ERROR: File already in the autorization list");
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +                    _fileListAuthorize.Add(Path.GetFileName(fileDialog.FileName), fileDialog.FileName);
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +                    addDirList(fileDialog.FileName);
Done

2020-12-10 18:47 UTC, yoanVESSIERE commented on App/TabTemplate.cs
> +                    addDirList(fileDialog.FileName);
Done

2020-12-10 18:48 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
>          private void Form1_DragDrop(object sender, DragEventArgs e)
So you can resolve the comment

2020-12-10 18:50 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                        childProcess.Kill();
@AntoineMaillard06 Do you want me to check is the process i will kill is the right one ?

2020-12-10 18:51 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +            if (collection.Count > 0)
Done

2020-12-10 19:47 UTC, Vaati3 submitted a review, later dismissed

2020-12-11 10:09 UTC, theocerutti requested changes

2020-12-11 10:09 UTC, theocerutti commented on App/LycaniteApplication.cs
> +                    }
Duplicated code

2020-12-11 10:09 UTC, theocerutti commented on App/LycaniteApplication.cs
> +                }
Duplicated code

2020-12-11 10:28 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +        private static void KillAllProcessesSpawnedBy(UInt32 parentProcessId)
I removed this function, and change the way of functionning of that.
Now the tab cannot be close until the process is fully closed by the user

2020-12-11 10:28 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                    }
Done

2020-12-11 10:28 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                }
Done

2020-12-11 10:31 UTC, theocerutti submitted a review, later dismissed

2020-12-11 13:26 UTC, Vaati3 submitted a review, later dismissed

2020-12-12 09:49 UTC, MathildeCouston approved these changes

2020-12-12 09:50 UTC, cyrilbegard approved these changes

2020-12-13 17:39 UTC, Shiranuit commented
Tested with Ransomeware, Ransomeware got fucked

2020-12-13 18:07 UTC, theocerutti approved these changes

2020-12-13 18:08 UTC, AntoineMaillard06 requested changes

2020-12-13 18:08 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
> +                case ELycaniteEventType.PROCESS_REQPERM:
useless `case`, may could you let only default or just nothing because default case ise useless too.

2020-12-13 18:10 UTC, cyrilbegard approved these changes

2020-12-13 18:11 UTC, yoanVESSIERE commented on App/LycaniteApplication.cs
> +                case ELycaniteEventType.PROCESS_REQPERM:
This is to prepare the futur changes, this one is currently in WIP so we let it like that

2020-12-13 18:11 UTC, AntoineMaillard06 commented on App/LycaniteApplication.cs
> +                case ELycaniteEventType.PROCESS_REQPERM:
ok

2020-12-13 18:12 UTC, AntoineMaillard06 approved these changes
incredible 1st prototype

2020-12-13 18:12 UTC, mic16 approved these changes

2020-12-13 18:14 UTC, Shiranuit approved these changes

2020-12-13 18:14 UTC, merged